name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted   # Use your EC2 self-hosted runner

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 3️⃣ Sync Prisma DB
      - name: Sync Prisma DB
        run: npx prisma db push --accept-data-loss

      # 4️⃣ Build backend
      - name: Build backend
        run: npm run build

     - name: Start/Restart Backend
  run: |
    cd /home/ubuntu/actions-runner/_work/sajag-backend/sajag-backend
    pm2 describe sajag-backend || pm2 start dist/index.js --name "sajag-backend"
    pm2 restart sajag-backend
    pm2 save
