name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted   # ✅ This tells GitHub to use your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Sync Prisma DB
        run: npx prisma db push --accept-data-loss

      - name: Build
        run: npm run build
