name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted   # Use your EC2 self-hosted runner

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 3️⃣ Sync Prisma DB
      - name: Sync Prisma DB
        run: npx prisma db push --accept-data-loss

      # 4️⃣ Build backend
      - name: Build backend
        run: npm run build

      # 5️⃣ Start or restart backend via PM2
      - name: Start/Restart Backend
        run: |
          # If process doesn't exist, start it
          pm2 describe sajag-backend || pm2 start npm --name "sajag-backend" -- run start
          # Restart to pick up latest code
          pm2 restart sajag-backend
          # Save PM2 process list for auto-start on reboot
          pm2 save
