name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted   # EC2 self-hosted runner

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Create .env file from GitHub secret
      - name: Create .env file
        run: |
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
          echo "✅ .env file created successfully"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Sync Prisma DB (will read DATABASE_URL from .env)
      - name: Sync Prisma DB
        run: npx prisma db push --accept-data-loss

      # 5️⃣ Build backend
      - name: Build backend
        run: npm run build

      # 6️⃣ Start or restart backend with PM2
      - name: Start/Restart Backend
        run: |
          pm2 describe sajag-backend || pm2 start npm --name "sajag-backend" -- run start
          pm2 restart sajag-backend
          pm2 save
